language: python

services:
  - postgresql

before_script:
- psql -c 'create database fastfood;' -U postgres
- pip install -r requirements.txt

script:
  - pytest -v
  - coverage run -m pytest
  - coverage report

after_success:
- coveralls
