version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
  test_db:
    image: postgres
  web:
    build: .
    command: python run.py
    volumes:
      - .:/FASTFOOD-FLASK
    ports:
      - "5000:5000"
    depends_on:
      - db
