version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/FASTFOOD-FLASK
    ports:
      - "5000:5000"
    depends_on:
      - db
